export const AUTOMATIC_PLAN_REQUEST_VERSION = '4.0.0' as const;
export const AUTOMATIC_PLAN_POLICY_VERSION = '8.0.0' as const;
export const AUTOMATIC_PLAN_OBJECTIVE_VERSION = '7.0.0' as const;
export const AUTOMATIC_PLAN_CALENDAR_VERSION = '1.0.0' as const;
export const AUTOMATIC_PLAN_FINGERPRINT_VERSION = '4.0.0' as const;
export const AUTOMATIC_PLAN_MODEL_VERSION = '4.0.0' as const;
export const AUTOMATIC_PLAN_MODEL_CERTIFICATE_VERSION = '4.0.0' as const;
export const AUTOMATIC_PLAN_RULESET_VERSION = '8.0.0' as const;
export const AUTOMATIC_PLAN_ENGINE_VERSION = '8.0.0' as const;

export const AUTOMATIC_PLAN_PRODUCT_TIME_LIMIT_MS = 1_800_000 as const;
export const AUTOMATIC_PLAN_MAX_ACTIVE_MEMBERS = 57 as const;
export const AUTOMATIC_PLAN_QUALIFICATION_THRESHOLD = 300 as const;
export const AUTOMATIC_PLAN_TARGET_700_RECOMMENDED_EQUIVALENT_UNITS = 8 as const;

export const AUTOMATIC_PLAN_FIELD_ORDER = Object.freeze([
  'PVP',
  'SELF_LEFT',
  'SELF_RIGHT',
] as const);

export const AUTOMATIC_PLAN_OBJECTIVE_STAGE_ORDER = Object.freeze([
  'TOTAL_NEW_PV',
  'ROOT_COMMISSION_GOAL_SHORTFALL',
  'CONFIRMED_PAYOUT_WON',
  'DISCARDED_EXCESS',
  'HIGH_TARGET_DESCENDING_EQUIVALENT_UNIT_SHORTFALL_VECTOR',
  'TARGET_700_DESCENDING_EQUIVALENT_UNIT_SHORTFALL_VECTOR',
  'FUTURE_CUMULATIVE_PVP_INVESTMENT',
  'NON_HUNDRED_CELLS',
  'MAX_DIRECT_PVP',
  'DETERMINISTIC_ALLOCATION_VECTOR',
] as const);
