export const AUTOMATIC_PLAN_SCALAR_OBJECTIVE_STAGES = Object.freeze([
  'TOTAL_NEW_PV',
  'CONFIRMED_PAYOUT_WON',
  'DISCARDED_EXCESS',
  'FUTURE_CUMULATIVE_PVP_INVESTMENT',
  'NON_HUNDRED_CELLS',
  'MAX_DIRECT_PVP',
] as const);

export const AUTOMATIC_PLAN_PROVEN_SCALAR_OBJECTIVE_COUNT =
  AUTOMATIC_PLAN_SCALAR_OBJECTIVE_STAGES.length;

export const AUTOMATIC_PLAN_VECTOR_OBJECTIVE_STAGES = Object.freeze([
  'HIGH_TARGET_ASCENDING_VECTOR',
  'TARGET_700_ASCENDING_VECTOR',
  'DETERMINISTIC_ALLOCATION_VECTOR',
] as const);

export const AUTOMATIC_PLAN_FINAL_VECTOR_OBJECTIVE =
  'DETERMINISTIC_ALLOCATION_VECTOR' as const;
