export const AUTOMATIC_PLAN_SCALAR_OBJECTIVE_STAGES = Object.freeze([
  'NON_ROOT_COMMISSION_EQUIVALENT_UNITS',
  'ROOT_COMMISSION_GOAL_SHORTFALL',
  'CONFIRMED_PAYOUT_WON',
  'TOTAL_NEW_PV',
  'DISCARDED_EXCESS',
  'FUTURE_CUMULATIVE_PVP_INVESTMENT',
  'NON_HUNDRED_CELLS',
  'MAX_DIRECT_PVP',
] as const);

export const AUTOMATIC_PLAN_PROVEN_SCALAR_OBJECTIVE_COUNT =
  AUTOMATIC_PLAN_SCALAR_OBJECTIVE_STAGES.length;

export const AUTOMATIC_PLAN_VECTOR_OBJECTIVE_STAGES = Object.freeze([
  'NON_ROOT_BASE_ENTITLEMENT_DESCENDING_EQUIVALENT_UNIT_SHORTFALL_VECTOR',
  'NON_ROOT_STRUCTURAL_OPPORTUNITY_DESCENDING_EQUIVALENT_UNIT_SHORTFALL_VECTOR',
  'DETERMINISTIC_ALLOCATION_VECTOR',
] as const);

export const AUTOMATIC_PLAN_FINAL_VECTOR_OBJECTIVE =
  'DETERMINISTIC_ALLOCATION_VECTOR' as const;
